=== tcrurav/ClassExercises-DAM-LND-23-24/Schools/schools.dtd
<!ELEMENT schools (school*)>
<!ELEMENT school (name,address,students)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT students (student*)>
<!ELEMENT student (studentName,studentSurname)>
<!ELEMENT studentName (#PCDATA)>
<!ELEMENT studentSurname (#PCDATA)>
<!ATTLIST student dni CDATA #IMPLIED>

=== tcrurav/ClassExercises-DAM-LND-23-24/Schools/schools.xml
<!-- Well-formed document -->
<!DOCTYPE schools SYSTEM "schools.dtd">

<schools>
  <school>
    <name>IES El Rincón</name>
    <address>Av. José Sánchez Peñate, s/n</address>
    <students>
      <student dni="52345653a">
        <studentName>Ancor</studentName>
        <studentSurname>García</studentSurname>
      </student>
      <student>
        <studentName>Sergio</studentName>
        <studentSurname>Cáceres</studentSurname>
      </student>
    </students>
  </school>
  <school>
    <name>IES Siete Palmas</name>
    <address>Av. Felo Monzón, 7</address>
    <students>
      <student>
        <studentName>Pepillo</studentName>
        <studentSurname>De los palotes</studentSurname>
      </student>
      <student>
        <studentName>Juanillo</studentName>
        <studentSurname>Alfonso</studentSurname>
      </student>
    </students>
  </school>
</schools>
