=== tcrurav/ClassExercises-DAM-LND-23-24/Students/students.dtd
<!ELEMENT buildings (building+)>
<!ELEMENT building (students?, teachers)>
<!ELEMENT students (student*)>
<!ELEMENT student (student_name, student_surname)>
<!ELEMENT teachers (teacher*)>
<!ELEMENT teacher (teacher_name, teacher_surname)>
<!ELEMENT teacher_name (#PCDATA)>
<!ELEMENT teacher_surname (#PCDATA)>
<!ELEMENT student_name (#PCDATA)>
<!ELEMENT student_surname (#PCDATA)>
<!ATTLIST student dni CDATA #IMPLIED>

<!-- <!ELEMENT building (students*,teachers*)> -->
<!-- <!ELEMENT building (students,teachers)*> -->
<!-- <!ELEMENT building (students,)> -->

=== tcrurav/ClassExercises-DAM-LND-23-24/Students/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE buildings SYSTEM "students.dtd">
<buildings>
  <building>
    <students>
      <student dni="6038927593A">
        <student_name>isaac</student_name>
        <student_surname>Ramos</student_surname>
      </student>
      <student>
        <student_name>Alejandro</student_name>
        <student_surname>Yanez</student_surname>
      </student>
      <student>
        <student_name>isaac</student_name>
        <student_surname>Ramos</student_surname>
      </student>
    </students>
    <teachers>
      <teacher>
        <teacher_name>Tiburcio</teacher_name>
        <teacher_surname>Cruz</teacher_surname>
      </teacher>
    </teachers>
  </building>
  <building>
    <students>
      <student>
        <student_name>isaac</student_name>
        <student_surname>Ramos</student_surname>
      </student>
      <student>
        <student_name>Alejandro</student_name>
        <student_surname>Yanez</student_surname>
      </student>
      <student>
        <student_name>isaac</student_name>
        <student_surname>Ramos</student_surname>
      </student>
    </students>
    <teachers>
      <teacher>
        <teacher_name>Tiburcio</teacher_name>
        <teacher_surname>Cruz</teacher_surname>
      </teacher>
    </teachers>
  </building>
</buildings>
